"""
Report synthesis pipeline.
Combines BiomedCLIP scores + BLIP-2 captions → structured radiology-style report via Claude.
"""

import os
import anthropic
from PIL import Image

from models.clip_classifier import ChestXrayClassifier
from models.blip_captioner import ChestXrayCaptioner


REPORT_SYSTEM_PROMPT = """You are an AI assistant helping radiologists review chest X-ray findings.
You are given:
1. Condition probability scores from a medical vision model (BiomedCLIP)
2. Visual descriptions generated by an image captioning model (BLIP-2)

Your job is to synthesize these into a structured radiology-style report.

IMPORTANT RULES:
- Always include a disclaimer that this is AI-assisted analysis and NOT a clinical diagnosis
- If confidence is low, say so clearly
- Use standard radiology terminology
- Structure output as: FINDINGS / IMPRESSION / RECOMMENDATION
- Be concise and factual, do not hallucinate specifics not supported by the input"""


def build_prompt(clip_result: dict, blip_captions: dict) -> str:
    scores_text = "\n".join(
        f"  - {condition}: {score:.1%}"
        for condition, score in sorted(clip_result["scores"].items(), key=lambda x: -x[1])
    )

    captions_text = "\n".join(
        f"  {key.upper()}: {text}" for key, text in blip_captions.items()
    )

    confidence_note = (
        "⚠️ LOW CONFIDENCE: Top prediction score is below threshold. Treat with extra caution."
        if clip_result["low_confidence"]
        else f"Top prediction: {clip_result['top_condition']} ({clip_result['top_score']:.1%})"
    )

    return f"""## BiomedCLIP Classification Scores
{scores_text}

{confidence_note}

## BLIP-2 Visual Descriptions
{captions_text}

Please generate a structured radiology report based on the above."""


class ReportGenerator:
    def __init__(self, device: str = None):
        self.classifier = ChestXrayClassifier(device=device)
        self.captioner = ChestXrayCaptioner(device=device)
        self.client = anthropic.Anthropic(api_key=os.environ.get("ANTHROPIC_API_KEY"))

    def analyze(self, image: Image.Image) -> dict:
        """
        Full pipeline: image → CLIP scores + BLIP captions → Claude report.
        Returns all intermediate results plus the final report.
        """
        print("Running BiomedCLIP classification...")
        clip_result = self.classifier.classify(image)

        print("Running BLIP-2 captioning...")
        blip_captions = self.captioner.caption_with_questions(image)

        print("Synthesizing report with Claude...")
        prompt = build_prompt(clip_result, blip_captions)

        message = self.client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=1024,
            system=REPORT_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )
        report = message.content[0].text

        return {
            "clip": clip_result,
            "blip": blip_captions,
            "report": report,
        }


if __name__ == "__main__":
    import sys

    image_path = sys.argv[1] if len(sys.argv) > 1 else None
    if not image_path:
        print("Usage: python pipeline/report_generator.py <image_path>")
        sys.exit(1)

    image = Image.open(image_path).convert("RGB")
    generator = ReportGenerator()
    result = generator.analyze(image)

    print("\n" + "=" * 60)
    print("GENERATED REPORT")
    print("=" * 60)
    print(result["report"])
